name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Install Dependencies
        run: flutter packages get
      - name: Github Config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
      - name: Deploy
        run: dart pub global activate peanut && flutter pub global run peanut --web-renderer canvaskit && git push origin --set-upstream gh-pages

